<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Access Codes Export</title>
    <style>
        :root {
            --primary-maroon: #800020;
            --primary-gold: #FFD700;
            --dark-maroon: #5C0016;
            --text-dark: #1F2937;
            --text-gray: #6B7280;
            --border-gray: #E5E7EB;
            --white: #FFFFFF;
            --light-gray: #F9FAFB;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        @page {
            size: A4;
            margin: 0.75in;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: var(--text-dark);
            line-height: 1.4;
            background: var(--white);
            font-size: 10pt;
        }

        .report-header {
            text-align: center;
            margin-bottom: 25px;
            padding-bottom: 15px;
            border-bottom: 2px solid var(--primary-maroon);
        }

        .university-name {
            font-size: 16pt;
            font-weight: bold;
            color: var(--primary-maroon);
            margin-bottom: 5px;
            text-transform: uppercase;
        }

        .department-name {
            font-size: 12pt;
            color: var(--text-dark);
            margin-bottom: 8px;
        }

        .report-title {
            font-size: 14pt;
            font-weight: bold;
            color: var(--text-dark);
            margin-top: 10px;
        }

        .report-info {
            margin-bottom: 20px;
            font-size: 9pt;
            color: var(--text-gray);
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 9pt;
        }

        thead {
            background-color: var(--primary-maroon);
            color: var(--white);
        }

        th {
            padding: 10px 8px;
            text-align: left;
            font-weight: bold;
            border: 1px solid var(--dark-maroon);
        }

        td {
            padding: 8px;
            border: 1px solid var(--border-gray);
            vertical-align: top;
        }

        tbody tr:nth-child(even) {
            background-color: var(--light-gray);
        }

        tbody tr:hover {
            background-color: #F3F4F6;
        }

        .name-column {
            width: 50%;
        }

        .access-code-column {
            width: 50%;
            font-family: 'Courier New', monospace;
            font-weight: bold;
            color: var(--primary-maroon);
        }

        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid var(--border-gray);
            font-size: 8pt;
            color: var(--text-gray);
            text-align: center;
        }

        .no-data {
            text-align: center;
            padding: 40px;
            color: var(--text-gray);
            font-style: italic;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="report-header">
        <div class="university-name">Eastern Visayas State University</div>
        <div class="report-title">Applicant Access Codes</div>
    </div>

    <div class="report-info">
        Generated on: {{ $generated_at }}<br>
        Generated by: {{ $generated_by }}
    </div>

    @if(count($applicants) > 0)
        <table>
            <thead>
                <tr>
                    <th class="name-column">Name</th>
                    <th class="access-code-column">Access Code</th>
                </tr>
            </thead>
            <tbody>
                @foreach($applicants as $applicant)
                    <tr>
                        <td>{{ $applicant['name'] }}</td>
                        <td class="access-code-column">{{ $applicant['access_code'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>Total Applicants: {{ count($applicants) }}</p>
            <p style="margin-top: 5px;">This document contains sensitive access codes. Please keep it secure and only share with authorized school officers.</p>
        </div>
    @else
        <div class="no-data">
            <p>No applicants with access codes found.</p>
        </div>
    @endif
</body>
</html>

