<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Geographic Performance Report</title>
    <style>
        :root {
            --primary-maroon: #800020;
            --primary-gold: #FFD700;
            --dark-maroon: #5C0016;
            --text-dark: #1F2937;
            --text-gray: #6B7280;
            --border-gray: #E5E7EB;
            --white: #FFFFFF;
            --light-gray: #F9FAFB;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        @page {
            size: A4 landscape;
            margin: 0.5in;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: var(--text-dark);
            line-height: 1.4;
            background: var(--white);
            font-size: 9pt;
        }

        .report-header {
            text-align: center;
            margin-bottom: 15px;
            padding-bottom: 10px;
            border-bottom: 2px solid var(--primary-maroon);
        }

        .university-name {
            font-size: 14pt;
            font-weight: bold;
            color: var(--primary-maroon);
            margin-bottom: 3px;
            text-transform: uppercase;
        }

        .campus-name {
            font-size: 11pt;
            color: var(--text-dark);
            margin-bottom: 8px;
        }

        .report-title {
            font-size: 13pt;
            font-weight: bold;
            color: var(--dark-maroon);
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .report-meta {
            font-size: 8pt;
            color: var(--text-gray);
            margin-bottom: 15px;
        }

        .meta-item {
            display: inline-block;
            margin-right: 20px;
        }

        .summary-boxes {
            display: table;
            width: 100%;
            margin-bottom: 15px;
        }

        .summary-box {
            display: table-cell;
            padding: 10px;
            background: var(--light-gray);
            border: 1px solid var(--border-gray);
            text-align: center;
            width: 25%;
        }

        .summary-value {
            font-size: 18pt;
            font-weight: bold;
            color: var(--primary-maroon);
        }

        .summary-label {
            font-size: 8pt;
            color: var(--text-gray);
            margin-top: 3px;
        }

        .section-title {
            font-size: 11pt;
            font-weight: bold;
            color: var(--primary-maroon);
            margin: 15px 0 10px 0;
            padding-bottom: 5px;
            border-bottom: 1px solid var(--border-gray);
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 8.5pt;
        }

        th {
            background: var(--primary-maroon);
            color: var(--white);
            padding: 8px 6px;
            text-align: left;
            font-weight: bold;
            font-size: 8.5pt;
        }

        td {
            padding: 6px;
            border-bottom: 1px solid var(--border-gray);
        }

        tr:nth-child(even) {
            background: var(--light-gray);
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .highlight-row {
            background: #FFF9E6 !important;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid var(--border-gray);
            font-size: 8pt;
            color: var(--text-gray);
        }

        .signature-section {
            margin-top: 40px;
            display: table;
            width: 100%;
        }

        .signature-box {
            display: table-cell;
            width: 50%;
            text-align: center;
        }

        .signature-line {
            border-top: 1px solid var(--text-dark);
            margin: 50px 30px 5px 30px;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="report-header">
        <div class="university-name">Eastern Visayas State University</div>
        <div class="campus-name">Ormoc City Campus</div>
        <div class="report-title">Geographic Performance Report</div>
    </div>

    <!-- Meta Information -->
    <div class="report-meta">
        <div class="meta-item"><strong>Generated:</strong> {{ $generatedAt }}</div>
        <div class="meta-item"><strong>Generated By:</strong> {{ $generatedBy }}</div>
        @if(isset($filters['province']) && $filters['province'] !== 'all')
            <div class="meta-item"><strong>Province Filter:</strong> {{ $filters['province'] }}</div>
        @endif
        @if(isset($filters['status']) && $filters['status'] !== 'all')
            <div class="meta-item"><strong>Status Filter:</strong> {{ ucfirst(str_replace('-', ' ', $filters['status'])) }}</div>
        @endif
    </div>

    <!-- Summary Statistics -->
    <div class="summary-boxes">
        <div class="summary-box">
            <div class="summary-value">{{ $totalApplicants }}</div>
            <div class="summary-label">Total Applicants</div>
        </div>
        <div class="summary-box">
            <div class="summary-value">{{ $totalProvinces }}</div>
            <div class="summary-label">Provinces Represented</div>
        </div>
        <div class="summary-box">
            <div class="summary-value">{{ $topProvince['province'] ?? 'N/A' }}</div>
            <div class="summary-label">Top Province</div>
        </div>
        <div class="summary-box">
            <div class="summary-value">{{ $topProvince['count'] ?? 0 }}</div>
            <div class="summary-label">Applicants from Top Province</div>
        </div>
    </div>

    <!-- Province Performance Table -->
    <div class="section-title">📍 Performance by Province</div>
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 25%;">Province</th>
                <th style="width: 12%;" class="text-center">Applicants</th>
                <th style="width: 15%;" class="text-center">Avg Exam Score</th>
                <th style="width: 15%;" class="text-center">Avg Overall Rating</th>
                <th style="width: 13%;" class="text-center">Exam Completed</th>
                <th style="width: 15%;" class="text-center">Admitted</th>
            </tr>
        </thead>
        <tbody>
            @forelse($provinceData as $index => $data)
                <tr class="{{ $index === 0 ? 'highlight-row' : '' }}">
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ $data['province'] }}</td>
                    <td class="text-center"><strong>{{ $data['count'] }}</strong></td>
                    <td class="text-center">{{ number_format($data['avg_exam_score'], 2) }}%</td>
                    <td class="text-center">{{ number_format($data['avg_overall_rating'], 2) }}</td>
                    <td class="text-center">{{ $data['exam_completed'] }}</td>
                    <td class="text-center">{{ $data['admitted'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="text-center">No data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Top Cities Performance Table -->
    <div class="section-title">🏙️ Top 10 Cities/Municipalities</div>
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 35%;">City/Municipality</th>
                <th style="width: 30%;">Province</th>
                <th style="width: 15%;" class="text-center">Applicants</th>
                <th style="width: 15%;" class="text-center">Avg Exam Score</th>
            </tr>
        </thead>
        <tbody>
            @forelse($cityData as $index => $data)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>{{ $data['city'] }}</td>
                    <td>{{ $data['province'] }}</td>
                    <td class="text-center"><strong>{{ $data['count'] }}</strong></td>
                    <td class="text-center">{{ number_format($data['avg_exam_score'], 2) }}%</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center">No data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <div style="text-align: center; margin-bottom: 10px;">
            <strong>Eastern Visayas State University - Ormoc City Campus</strong><br>
            Automated Report Generation System
        </div>
        <div style="text-align: center; font-size: 7pt;">
            This is a computer-generated report. Generated on {{ $generatedAt }}
        </div>
    </div>

    <!-- Signature Section -->
    <div class="signature-section">
        <div class="signature-box">
            <div class="signature-line">
                <strong>Prepared By</strong><br>
                {{ $generatedBy }}
            </div>
        </div>
        <div class="signature-box">
            <div class="signature-line">
                <strong>Reviewed By</strong><br>
                Department Head
            </div>
        </div>
    </div>
</body>
</html>

