<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 16px;
            margin: 0 0 5px 0;
            font-weight: bold;
        }
        .header p {
            font-size: 9px;
            margin: 2px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #000;
            padding: 4px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
            font-size: 9px;
        }
        td {
            font-size: 8px;
        }
        .text-center {
            text-align: center;
        }
        .section-title {
            font-weight: bold;
            margin-top: 15px;
            margin-bottom: 5px;
            font-size: 11px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $reportTitle }}</h1>
        <p>Generated by: {{ $instructor->name }}</p>
        <p>Date: {{ $generatedAt }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">#</th>
                <th style="width: 15%;">Name</th>
                <th style="width: 10%;">Application No.</th>
                <th style="width: 12%;">Email</th>
                <th style="width: 8%;">Phone</th>
                <th style="width: 8%;">Exam Score</th>
                <th style="width: 10%;">Interview Status</th>
                <th style="width: 10%;">Interview Date</th>
                <th style="width: 23%;">Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($applicants as $index => $applicant)
            @php
                $interview = $applicant->latestInterview;
                $hasCompletedInterview = $applicant->interviews()->where('status', 'completed')->exists();
            @endphp
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $applicant->first_name }} {{ $applicant->last_name }}</td>
                <td>{{ $applicant->application_no }}</td>
                <td>{{ $applicant->email_address }}</td>
                <td>{{ $applicant->phone_number ?? '-' }}</td>
                <td class="text-center">{{ $applicant->enrollassess_score ? number_format($applicant->enrollassess_score, 2) . '%' : '-' }}</td>
                <td class="text-center">{{ ucwords(str_replace('-', ' ', $applicant->status)) }}</td>
                <td class="text-center">{{ $interview && $interview->schedule_date ? $interview->schedule_date->format('M d, Y') : '-' }}</td>
                <td>{{ $interview && $interview->remarks ? Str::limit($interview->remarks, 150) : '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>

