<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTitle }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 16px;
            margin: 0 0 5px 0;
            font-weight: bold;
        }
        .header p {
            font-size: 9px;
            margin: 2px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #000;
            padding: 4px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
            font-weight: bold;
            font-size: 9px;
        }
        td {
            font-size: 8px;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $reportTitle }}</h1>
        <p>Generated by: {{ $instructor->name }}</p>
        <p>Date: {{ $generatedAt }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 4%;">#</th>
                <th style="width: 12%;">Name</th>
                <th style="width: 10%;">Application No.</th>
                <th style="width: 8%;">Interview Date</th>
                <th style="width: 6%;">Comm</th>
                <th style="width: 6%;">Motiv</th>
                <th style="width: 6%;">Prob</th>
                <th style="width: 6%;">Prog</th>
                <th style="width: 6%;">Pers</th>
                <th style="width: 6%;">IT</th>
                <th style="width: 6%;">Learn</th>
                <th style="width: 6%;">Imp</th>
                <th style="width: 7%;">Overall</th>
                <th style="width: 10%;">Recommend</th>
                <th style="width: 6%;">GWA</th>
                <th style="width: 5%;">Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($applicants as $index => $applicant)
            @php
                $interview = $applicant->interviews()->where('status', 'completed')->first();
            @endphp
            @if($interview)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $applicant->first_name }} {{ $applicant->last_name }}</td>
                <td>{{ $applicant->application_no }}</td>
                <td class="text-center">{{ $interview->schedule_date ? $interview->schedule_date->format('M d, Y') : '-' }}</td>
                <td class="text-center">{{ $interview->communication_skills ?? '-' }}</td>
                <td class="text-center">{{ $interview->motivation_interest ?? '-' }}</td>
                <td class="text-center">{{ $interview->problem_solving_attitude ?? '-' }}</td>
                <td class="text-center">{{ $interview->program_understanding ?? '-' }}</td>
                <td class="text-center">{{ $interview->personality_attitude ?? '-' }}</td>
                <td class="text-center">{{ $interview->it_background ?? '-' }}</td>
                <td class="text-center">{{ $interview->willingness_to_learn ?? '-' }}</td>
                <td class="text-center">{{ $interview->overall_impression ?? '-' }}</td>
                <td class="text-center">{{ $interview->overall_score ? number_format($interview->overall_score, 1) : '-' }}</td>
                <td class="text-center">{{ $interview->recommendation ? ucwords(str_replace('_', ' ', $interview->recommendation)) : '-' }}</td>
                <td class="text-center">{{ $applicant->card_tor_gwa ? number_format($applicant->card_tor_gwa, 2) : '-' }}</td>
                <td>{{ $interview->remarks ? Str::limit($interview->remarks, 30) : '-' }}</td>
            </tr>
            @endif
            @endforeach
        </tbody>
    </table>
</body>
</html>

